services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pewsDatabase
      - SPRING_DATASOURCE_USERNAME=rootdb
      - SPRING_DATASOURCE_PASSWORD=rootdb
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER= rootdb
      - POSTGRES_PASSWORD= rootdb
      - POSTGRES_DB= pewsDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  volumes:
    postgres_data: {}