services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=rootdb
      - POSTGRES_PASSWORD=rootdb
      - POSTGRES_DB=pewsDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rootdb", "-d", "pewsDatabase"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pewsback-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pewsDatabase
      - SPRING_DATASOURCE_USERNAME=rootdb
      - SPRING_DATASOURCE_PASSWORD=rootdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - JWT_PRIVATE_KEY_PATH=/keys/private_key.pem
      - JWT_PUBLIC_KEY_PATH=/keys/public_key.pem
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./keys:/keys
volumes:
  postgres_data: